"use client";

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";

export type Language = "zh" | "en";

type CopyValues = Record<string, number | string>;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (source: string, values?: CopyValues) => string;
};

const defaultLanguage: Language = "zh";
export const languageStorageKey = "marketpilot:language";

const englishCopy: Record<string, string> = {
  "MarketPilot": "MarketPilot",
  "商机顾问 Agent": "Opportunity Advisor Agent",
  "小成本商机顾问": "Lean Opportunity Advisor",
  "从需求、供给、竞品和风险里，筛出值得快速验证的小生意机会。":
    "Screen demand, supply, competitors, and risk to find small-business opportunities worth validating quickly.",
  "从需求、供给、竞品和风险中发现可快速验证的小生意机会。":
    "Find low-cost business opportunities by connecting demand, supply, competitors, and risk.",
  "来源、供给、竞品、风险和验证计划会在后续切片中逐步展开。":
    "Sources, supply, competitors, risk, and validation plans will unfold in upcoming slices.",
  "主导航": "Primary navigation",
  "用户菜单": "User menu",
  "演示用户": "Demo user",
  "内部质量复查": "Internal quality review",
  "切换语言": "Language",
  "中文": "Chinese",
  "English": "English",
  "面包屑导航": "Breadcrumb navigation",

  "新建研究": "New research",
  "我的研究": "My research",
  "研究记录": "Research records",
  "研究任务": "Research tasks",
  "商机推荐": "Opportunities",
  "基础商机推荐": "Basic opportunity recommendations",
  "最终报告": "Final report",
  "研究历史": "Research history",
  "研究进度": "Research progress",
  "商机详情": "Opportunity detail",
  "基础报告": "Basic report",
  "从这里进入新建研究、查看运行状态，并继续浏览商机推荐与最终报告。":
    "Start new research, check run status, and continue into opportunity recommendations and final reports.",
  "统一查看进行中、已完成和失败的研究，并从同一入口继续进度或阅读结果。":
    "Review in-progress, completed, and failed research in one place, then continue progress or read results from the same entry.",
  "统一查看进行中、已完成和失败的真实研究。":
    "Review real in-progress, completed, and failed research in one place.",
  "描述你想尝试的小生意方向，后续任务闭环会在这里创建真实研究任务。":
    "Describe the small business direction you want to test; this flow will create a real research task.",
  "展示某条研究任务生成的 3-5 个待验证商机草案。":
    "Shows 3-5 draft opportunities generated by a research task.",
  "选择一条已完成研究任务后，查看对应的基础报告和待验证商机摘要。":
    "Select a completed research task to view its basic report and draft opportunity summary.",
  "选择研究结果": "Select research results",
  "报告需要绑定一条真实研究。请先从我的研究里选择已完成任务。":
    "Reports must be tied to real research. Choose a completed task from My research first.",
  "回看真实研究任务，并从历史记录继续查看报告、进度或重新运行。":
    "Review real research tasks and continue to reports, progress, or reruns.",
  "查看当前任务运行到哪一步、哪些阶段已完成，以及失败或完成后的下一步操作。":
    "See the current task stage, completed steps, and next actions after failure or completion.",
  "集中查看单个待验证商机是什么、为什么推荐、适合谁、风险高低和下一步做什么。":
    "Review what a single draft opportunity is, why it is recommended, who it fits, risk level, and next steps.",
  "基于已生成商机结果汇总推荐排序、风险等级和下一步行动摘要。":
    "Summarizes recommendation ranking, risk level, and next actions from generated opportunity results.",

  "查看任务": "View tasks",
  "返回研究任务": "Back to research tasks",
  "返回我的研究": "Back to my research",
  "请选择一条已完成任务": "Select a completed task",
  "报告需要绑定真实研究任务，避免把静态演示内容误当成本次研究结果。":
    "Reports must be tied to real research tasks so static demo content is not mistaken for this run.",
  "请选择一条研究任务": "Select a research task",
  "商机推荐需要从已完成的真实研究任务进入。":
    "Opportunity recommendations must be opened from a completed real research task.",
  "商机推荐需要从我的研究中选择一条已完成的真实研究进入。":
    "Open opportunity recommendations by choosing a completed real research item from My research.",
  "还没有生成商机": "No opportunities generated yet",
  "任务可能仍在运行，或本次运行尚未产出可展示的基础推荐。":
    "The task may still be running, or this run has not produced displayable recommendations yet.",

  "进度": "Progress",
  "商机": "Opportunities",
  "报告": "Report",
  "来源线索": "Sources",
  "来源 {count}": "Sources {count}",
  "任务上下文导航": "Task context navigation",
  "还没有真实研究任务": "No real research tasks yet",
  "首次演示可以直接启动下面的中文示例；创建后会进入真实任务进度页。":
    "For the first demo, start one of the Chinese samples below; after creation, it opens the real task progress page.",

  "运行中": "Running",
  "失败": "Failed",
  "完成": "Completed",
  "已创建": "Created",
  "已完成": "Completed",
  "待启动": "Ready",
  "排队中": "Queued",
  "正在生成基础商机推荐，后续会展示实时阶段和进度。":
    "Generating basic opportunity recommendations. Live stages and progress will appear later.",
  "生成失败时展示原因，并提供重新运行入口。":
    "Failure reasons appear here, with a rerun entry point.",
  "完成后进入商机推荐、商机详情和最终报告。":
    "After completion, continue to recommendations, opportunity details, and the final report.",
  "完成后进入研究结果，再切换商机推荐、基础报告和来源线索。":
    "After completion, open research results, then switch between opportunities, the basic report, and sources.",

  "需求已提交": "Intake submitted",
  "等待后台执行": "Waiting for worker",
  "整理研究需求": "Normalize intake",
  "生成基础推荐": "Generate recommendations",
  "校验推荐结果": "Validate results",
  "保存研究结果": "Persist results",
  "收集公开来源线索": "Collect public sources",
  "整理公开来源证据": "Index public evidence",
  "生成需求洞察": "Generate demand insights",
  "生成货源候选": "Generate supply candidates",
  "生成竞品参考": "Generate competitor references",
  "估算验证预算": "Estimate validation budget",
  "复核商机风险": "Review opportunity risks",
  "生成行动计划": "Create action plans",
  "基础推荐已生成": "Recommendations generated",
  "生成失败": "Generation failed",

  "研究任务列表": "Research task list",
  "正在加载真实研究任务。": "Loading real research tasks.",
  "正在加载": "Loading",
  "任务加载失败": "Failed to load tasks",
  "无法读取研究任务。": "Unable to read research tasks.",
  "重新加载": "Reload",
  "展示真实创建的任务和当前状态。":
    "Shows real created tasks and their current status.",
  "{count} 个任务": "{count} tasks",
  "{shown} / {total} 条记录": "{shown} / {total} records",
  "任务": "Task",
  "状态": "Status",
  "阶段摘要": "Stage summary",
  "创建时间": "Created at",
  "完整创建时间：{date}": "Full created date: {date}",
  "下一步": "Next step",
  "全部": "All",
  "进行中": "In progress",
  "未适用": "Not applicable",
  "查看结果": "View results",
  "查看研究结果": "View research results",
  "查看进度": "View progress",
  "重新运行": "Rerun",
  "开始研究": "Start research",
  "启动研究": "Start research",
  "更多操作": "More actions",
  "次要入口": "Secondary links",
  "研究记录分页": "Research records pagination",
  "第一页": "First page",
  "上一页": "Previous",
  "下一页": "Next",
  "最后一页": "Last page",
  "第 {page} / {totalPages} 页": "Page {page} / {totalPages}",
  "第 {page} 页": "Page {page}",
  "每页 {count} 条": "{count} per page",
  "每页条数": "Rows per page",
  "{count} 条/页": "{count} rows/page",

  "历史研究列表": "Research history list",
  "历史加载失败": "Failed to load history",
  "无法读取研究历史。": "Unable to read research history.",
  "真实任务的继续入口，按创建时间倒序展示。":
    "Continuation entries for real tasks, ordered newest first.",
  "{count} 条记录": "{count} records",
  "当前阶段": "Current stage",
  "可演示": "Demo-ready",
  "需复查": "Needs review",
  "检查失败": "Check failed",
  "未检查": "Unchecked",
  "已过期": "Stale",
  "检查读取中": "Loading check",
  "操作": "Actions",
  "当前筛选没有研究记录": "No research records for this filter",
  "当前没有{filter}状态的研究，可以切换筛选或新建研究。":
    "There are no research records in {filter}. Switch filters or start new research.",
  "查看全部": "View all",

  "研究需求": "Research brief",
  "提交后会创建真实研究任务，并启动基础商机推荐生成。":
    "Submitting creates a real research task and starts basic opportunity generation.",
  "自然语言需求": "Natural language brief",
  "用一句话描述预算、渠道、偏好品类和排除条件。":
    "Describe budget, channels, preferred categories, and exclusions in one sentence.",
  "验证预算": "Validation budget",
  "目标渠道": "Target channels",
  "目标人群": "Target audience",
  "期望利润": "Expected profit",
  "偏好品类": "Preferred categories",
  "排除品类": "Excluded categories",
  "供给来源偏好": "Supply source preferences",
  "其他限制条件": "Other constraints",
  "轻库存优先": "Light inventory first",
  "毛利 30%+": "Gross margin 30%+",
  "中文内容平台": "Chinese content platforms",
  "待验证推荐": "Draft recommendation",
  "正在启动": "Starting",
  "创建并启动": "Create and start",
  "中文示例需求": "Chinese sample briefs",
  "可以先填入表单微调，也可以直接启动一个完整演示任务。":
    "Fill the form first to edit, or directly start a complete demo task.",
  "填入表单": "Fill form",
  "启动示例": "Start sample",
  "打开已创建任务": "Open created task",
  "启动示例研究失败，请稍后重试。":
    "Failed to start sample research. Please try again later.",
  "创建任务失败，请稍后重试。":
    "Failed to create the task. Please try again later.",
  " 可以从任务列表或进度页继续启动。":
    " You can continue from the task list or progress page.",

  "正在准备任务结果视图。": "Preparing task result view.",
  "正在读取任务生成的待验证商机。":
    "Reading draft opportunities generated by the task.",
  "商机读取失败": "Failed to read opportunities",
  "无法读取商机结果。": "Unable to read opportunity results.",
  "返回任务": "Back to tasks",
  "基于任务输入生成的待验证草案，不包含来源或竞品核验。":
    "Draft recommendations based on the task input, without source or competitor validation.",
  "{count} 个推荐": "{count} recommendations",
  "排序": "Rank",
  "商机名称": "Opportunity name",
  "验证动作": "Validation action",
  "价格 / 风险": "Price / risk",
  "推荐优先级": "Priority",
  "风险 {level}": "Risk {level}",
  "低": "Low",
  "中": "Medium",
  "高": "High",
  "详情": "Details",
  "价格带": "Price band",
};

const languageContext = createContext<LanguageContextValue | null>(null);

export function normalizeLanguage(value: string | null): Language {
  return value === "en" ? "en" : defaultLanguage;
}

function formatCopy(template: string, values?: CopyValues) {
  if (!values) {
    return template;
  }

  return template.replace(/\{(\w+)\}/g, (match, key) =>
    Object.prototype.hasOwnProperty.call(values, key) ? String(values[key]) : match,
  );
}

export function LanguageProvider({
  children,
  initialLanguage = defaultLanguage,
}: {
  children: ReactNode;
  initialLanguage?: Language;
}) {
  const [language, setLanguageState] = useState<Language>(initialLanguage);

  useEffect(() => {
    document.documentElement.lang = language === "zh" ? "zh-CN" : "en";
    window.localStorage.setItem(languageStorageKey, language);
  }, [language]);

  const setLanguage = useCallback((nextLanguage: Language) => {
    setLanguageState(nextLanguage);
    window.localStorage.setItem(languageStorageKey, nextLanguage);
    document.cookie = `${languageStorageKey}=${nextLanguage}; path=/; max-age=31536000; samesite=lax`;
  }, []);

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage,
      t: (source, values) =>
        formatCopy(language === "en" ? englishCopy[source] ?? source : source, values),
    }),
    [language, setLanguage],
  );

  return (
    <languageContext.Provider value={value}>{children}</languageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(languageContext);

  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }

  return context;
}

export function LocalizedText({
  source,
  values,
}: {
  source: string;
  values?: CopyValues;
}) {
  const { t } = useLanguage();

  return <>{t(source, values)}</>;
}
